module.exports = {
  definitions: {},
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "http://example.com/root.json",
  type: "object",
  title: "The Plan Schema",
  required: [
    "planCostShares",
    "linkedPlanServices",
    "_org",
    "objectId",
    "objectType",
    "planType",
    "creationDate",
  ],
  properties: {
    planCostShares: {
      type: "object",
      title: "The PlanCostShares Schema",
      required: ["deductible", "_org", "copay", "objectId", "objectType"],
      properties: {
        deductible: {
          type: "number",
          title: "The deductible Schema",
          default: 0,
          examples: [2000],
        },
        _org: {
          type: "string",
          title: "The _org Schema",
          default: "",
          examples: ["example.com"],
          pattern: "^(.*)$",
        },
        copay: {
          type: "number",
          title: "The copay Schema",
          default: 0,
          examples: [23],
        },
        objectId: {
          type: "string",
          title: "The objectId Schema",
          default: "",
          examples: ["1234vxc2324sdf-501"],
          pattern: "^(.*)$",
        },
        objectType: {
          type: "string",
          title: "The objectType Schema",
          default: "",
          examples: ["membercostshare"],
          pattern: "^(.*)$",
        },
      },
    },
    linkedPlanServices: {
      type: "array",
      title: "The LinkedPlanServices Schema",
      items: {
        type: "object",
        title: "The Items Schema",
        required: [
          "linkedService",
          "planserviceCostShares",
          "_org",
          "objectId",
          "objectType",
        ],
        properties: {
          linkedService: {
            type: "object",
            title: "The LinkedService Schema",
            required: ["_org", "objectId", "objectType", "name"],
            properties: {
              _org: {
                type: "string",
                title: "The _org Schema",
                default: "",
                examples: ["example.com"],
                pattern: "^(.*)$",
              },
              objectId: {
                type: "string",
                title: "The objectId Schema",
                default: "",
                examples: ["1234520xvc30asdf-502"],
                pattern: "^(.*)$",
              },
              objectType: {
                type: "string",
                title: "The objectType Schema",
                default: "",
                examples: ["service"],
                pattern: "^(.*)$",
              },
              name: {
                type: "string",
                title: "The name Schema",
                default: "",
                examples: ["Yearly physical"],
                pattern: "^(.*)$",
              },
            },
          },
          planserviceCostShares: {
            type: "object",
            title: "The planserviceCostShares Schema",
            required: ["deductible", "_org", "copay", "objectId", "objectType"],
            properties: {
              deductible: {
                type: "number",
                title: "The Deductible Schema",
                default: 0,
                examples: [10],
              },
              _org: {
                type: "string",
                title: "The _org Schema",
                default: "",
                examples: ["example.com"],
                pattern: "^(.*)$",
              },
              copay: {
                type: "number",
                title: "The Copay Schema",
                default: 0,
                examples: [0],
              },
              objectId: {
                type: "string",
                title: "The objectId Schema",
                default: "",
                examples: ["1234512xvc1314asdfs-503"],
                pattern: "^(.*)$",
              },
              objectType: {
                type: "string",
                title: "The objectType Schema",
                default: "",
                examples: ["membercostshare"],
                pattern: "^(.*)$",
              },
            },
          },
          _org: {
            type: "string",
            title: "The _org Schema",
            default: "",
            examples: ["example.com"],
            pattern: "^(.*)$",
          },
          objectId: {
            type: "string",
            title: "The objectId Schema",
            default: "",
            examples: ["27283xvx9asdff-504"],
            pattern: "^(.*)$",
          },
          objectType: {
            type: "string",
            title: "The objectType Schema",
            default: "",
            examples: ["planservice"],
            pattern: "^(.*)$",
          },
        },
      },
    },
    _org: {
      type: "string",
      title: "The _org Schema",
      default: "",
      examples: ["example.com"],
      pattern: "^(.*)$",
    },
    objectId: {
      type: "string",
      title: "The objectId Schema",
      default: "",
      examples: ["12xvxc345ssdsds-508"],
      pattern: "^(.*)$",
    },
    objectType: {
      type: "string",
      title: "The objectType Schema",
      default: "",
      examples: ["plan"],
      pattern: "^(.*)$",
    },
    planType: {
      type: "string",
      title: "The planType Schema",
      default: "",
      examples: ["inNetwork"],
      pattern: "^(.*)$",
    },
    creationDate: {
      type: "string",
      title: "The creationDate Schema",
      default: "",
      examples: ["12-12-2017"],
      pattern: "^(.*)$",
    },
  },
};
